### ISSUE TITLE
Unable to create subdomains

### ISSUE THREAD

**Issue by geopayme** [ensdomains/subdomain-registrar#137]
When creating subdomains, there is no resolver or controller set. Fees are waisted to delete and create subdomains that can not resolve to a name. The name should be elenisara.alexanderthegreat.eth but I get a hash instead of a name

![alexanderthegreat eth 2021-06-01 11-41-46](https://user-images.githubusercontent.com/8299759/120293930-62b4ce00-c2ce-11eb-8e12-085769fa0251.png)

Even after we set the proper resolver details. the issue persists! 

![0x119bdce4845a86ffcf95a81a999350cead7d3b1fba0d01d6d8ec49f18ba3c7b9 alexanderthegreat eth 2021-06-01 11-42-22](https://user-images.githubusercontent.com/8299759/120294090-8841d780-c2ce-11eb-8f44-e86b6ac0ca76.png)

![0x54c7e2edfc7a63745f742a86b6f6736730e87c53053b4b0feb4faa5019470bf2 alexanderthegreat eth 2021-06-01 11-44-24](https://user-images.githubusercontent.com/8299759/120294305-bc1cfd00-c2ce-11eb-9694-38632606f14b.png)

**Comment by Arachnid** [comment]
Resolvers aren't currently automatically set when creating a subdomain. It doesn't look like you're setting a resolver on the subdomain, though - can you link to the transaction where you try to set it?

**Comment by geopayme** [comment]
Here is a tx but even with the resolver updated the subdomain is still an abstract number!

https://etherscan.io/tx/0xb4c83d670089a775125feef483d7f188c8f7cc05b24530e780c94f4de694fca7

**Comment by Arachnid** [comment]
You appear to have created the subdomain that way - by entering a hash into the field instead of a name.

**Comment by geopayme** [comment]
Why this works fine on this subdomain?

![smartprofile eth 2021-06-02 04-41-26](https://user-images.githubusercontent.com/8299759/120411074-dc939880-c35c-11eb-83a6-85eb081ab7f3.png)

with transaction https://etherscan.io/tx/0xfab4b69d5206029a5f3fcd3e8e16aea8f0841030cd8ebc928a8afd85b369c346

**Comment by geopayme** [comment]
No I created the subdomain with elenisara.alexanderthegreat.eth the system does not add the name properly

**Comment by Arachnid** [comment]
Ah. Names are not stored onchain in plain text form, so if the name isn't in our list of known names, the app can't show it to you. If you enter the name into the search field, it will populate it correctly.

**Comment by Arachnid** [comment]
If you'd like further support, please come to our Discord!

**Comment by geopayme** [comment]
Once again ETH waisted and now no subdomain created. the subdomain 

https://etherscan.io/tx/0x778601d1c76d1efbaded98c3a3308be8054d5c45299a7796af7a44929115dd7a


![alexanderthegreat eth 2021-06-02 04-46-26](https://user-images.githubusercontent.com/8299759/120411686-e2d64480-c35d-11eb-95a9-9b5d9a6bb696.png)
![alexanderthegreat eth 2021-06-02 04-46-10](https://user-images.githubusercontent.com/8299759/120411689-e36edb00-c35d-11eb-8555-c0dabbbc2d68.png)
![alexanderthegreat eth 2021-06-02 04-44-40](https://user-images.githubusercontent.com/8299759/120411691-e4077180-c35d-11eb-9fc5-4f1f6b0cf3a7.png)

**Comment by geopayme** [comment]
how chating with 200 people will resolve the platform issues I am discussing? I hope this is not another waisted defunck idea!

**Comment by Arachnid** [comment]
As I said - the domains exist, we just can't show the plaintext name because it's not in our dictionary: https://app.ens.domains/name/elenisara.alexanderthegreat.eth

Discord is our support channel, and is where you're likely to get the most interactive help for any issues you're encountering.
