### ISSUE TITLE
[Question] The paid subdomains, when bought, its owner receives it?

### ISSUE THREAD

**Issue by DaniellMesquita** [ensdomains/subdomain-registrar#65]

**Comment by Arachnid** [comment]
Sorry, I don't understand the question. Can you elaborate?

**Comment by DaniellMesquita** [comment]
I see some subdomains are paid. For who it comes?

**Comment by Arachnid** [comment]
The owner of the domain gets the funds, less any commission they decided to
set aside.

**Comment by magford** [comment]
@Arachnid I noticed enslisting has subdomains with annual renewal fees. ENSnow subdomains require a single transaction for the life of the registrar, correct? No rent / no yearly fees.

**Comment by Arachnid** [comment]
That's right.
